# Generated by Django 4.0.6 on 2022-07-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0011_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='arrivals_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='products_url',
        ),
    ]
